name: reformat files
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          black_args: .
      - uses: isort/isort-action@master
        with:
          configuration: --overwrite-in-place